#version 150
in vec3 localPosition;
in float edgeDistance;
in float panelSeed;
uniform vec3 Eye;
uniform float Opacity;
uniform float Time;
uniform vec4 Hole0;
uniform vec4 Hole1;
uniform vec4 Hole2;
uniform vec4 Hole3;
uniform vec4 Hole4;
uniform vec4 Hole5;
uniform vec4 Hole6;
uniform vec4 Hole7;
uniform vec4 Hole8;
uniform vec4 Hole9;
uniform vec4 Hole10;
uniform vec4 Hole11;
uniform vec4 Hole12;
uniform vec4 Hole13;
uniform vec4 Hole14;
uniform vec4 Hole15;
uniform vec4 Hole16;
uniform vec4 Hole17;
uniform vec4 Hole18;
uniform vec4 Hole19;
uniform vec4 Hole20;
uniform vec4 Hole21;
uniform vec4 Hole22;
uniform vec4 Hole23;
uniform vec4 Hole24;
uniform vec4 Hole25;
uniform vec4 Hole26;
uniform vec4 Hole27;
uniform vec4 Hole28;
uniform vec4 Hole29;
uniform vec4 Hole30;
uniform vec4 Hole31;
out vec4 fragColor;
float opening(vec4 hole) {
    if (hole.w < 0.0) return 10000.0;
    vec3 q = localPosition - hole.xyz;
    q.y = max(abs(q.y) - hole.w, 0.0);
    return length(q) - 1.05;
}
void main() {
    float gap = 10000.0;
    gap = min(gap, opening(Hole0));
    gap = min(gap, opening(Hole1));
    gap = min(gap, opening(Hole2));
    gap = min(gap, opening(Hole3));
    gap = min(gap, opening(Hole4));
    gap = min(gap, opening(Hole5));
    gap = min(gap, opening(Hole6));
    gap = min(gap, opening(Hole7));
    gap = min(gap, opening(Hole8));
    gap = min(gap, opening(Hole9));
    gap = min(gap, opening(Hole10));
    gap = min(gap, opening(Hole11));
    gap = min(gap, opening(Hole12));
    gap = min(gap, opening(Hole13));
    gap = min(gap, opening(Hole14));
    gap = min(gap, opening(Hole15));
    gap = min(gap, opening(Hole16));
    gap = min(gap, opening(Hole17));
    gap = min(gap, opening(Hole18));
    gap = min(gap, opening(Hole19));
    gap = min(gap, opening(Hole20));
    gap = min(gap, opening(Hole21));
    gap = min(gap, opening(Hole22));
    gap = min(gap, opening(Hole23));
    gap = min(gap, opening(Hole24));
    gap = min(gap, opening(Hole25));
    gap = min(gap, opening(Hole26));
    gap = min(gap, opening(Hole27));
    gap = min(gap, opening(Hole28));
    gap = min(gap, opening(Hole29));
    gap = min(gap, opening(Hole30));
    gap = min(gap, opening(Hole31));
    float cover = smoothstep(-0.10, 0.22, gap);
    if (cover < 0.005) discard;
    float aa = max(fwidth(edgeDistance), 0.008);
    float line = 1.0 - smoothstep(0.025, 0.025 + aa * 1.5, edgeDistance);
    float halo = exp(-max(edgeDistance, 0.0) * 8.0);
    vec3 view = normalize(Eye - localPosition + vec3(0.00001));
    float facing = dot(normalize(localPosition), view);
    float rim = pow(1.0 - abs(facing), 3.0);
    // Keep the near honeycomb legible through the transparent far hemisphere.
    float back = length(Eye) > length(localPosition) && facing < 0.0 ? 0.12 : 1.0;
    float pulse = 0.94 + 0.06 * sin(Time * 1.6 + panelSeed);
    float openingRim = exp(-abs(gap - 0.14) * 9.0);
    vec3 violet = vec3(0.62, 0.32, 0.78);
    vec3 color = mix(violet, vec3(0.96, 0.84, 1.0), clamp(line + rim * 0.65 + openingRim, 0.0, 1.0));
    float alpha = (0.10 + line * 0.68 + halo * 0.15 + rim * 0.20 + openingRim * 0.40) * pulse * back;
    fragColor = vec4(color, clamp(alpha * cover * Opacity, 0.0, 0.92));
}
